

hosts = ['example.com', 'abcvideo.cc', 'adultswim.com', 'amazon.com', 'anavids.com', 'ani-stream.com', 'aparat.cam',
         'wolfstream.tv', 'brupload.net', 'castamp.com', 'm.cda.pl', 'cda.pl', 'www.cda.pl', 'ebd.cda.pl', 'clicknupload.cc',
         'clicknupload.co', 'clicknupload.com', 'clicknupload.me', 'clicknupload.link', 'clicknupload.org', 'clipwatching.com',
         'highstream.tv', 'cloud9.to', 'cloud.mail.ru', 'cos.tv', 'dailymotion.com', 'dai.ly', 'daxab.com', 'dood.watch',
         'doodstream.com', 'dood.to', 'dood.so', 'dood.cx', 'dood.la', 'dood.ws', 'dood.sh', 'doodstream.co', 'easyload.io',
         'evoload.io', 'facebook.com', 'fastdrive.io', 'fastplay.sx', 'fastplay.cc', 'fastplay.to', 'fembed.com', 'anime789.com',
         '24hd.club', 'vcdn.io', 'sharinglink.club', 'votrefiles.club', 'femoload.xyz', 'feurl.com', 'dailyplanet.pw', 'jplayer.net',
         'xstreamcdn.com', 'gcloud.live', 'vcdnplay.com', 'vidohd.com', 'vidsource.me', 'votrefile.xyz', 'zidiplay.com', 'fcdn.stream',
         'mediashore.org', 'there.to', 'femax20.com', 'sexhd.co', 'viplayer.cc', 'mrdhan.com', 'votrefilms.xyz', 'embedsito.com',
         'dutrag.com', 'youvideos.ru', 'streamm4u.club', 'moviepl.xyz', 'asianclub.tv', 'vidcloud.fun', 'fplayer.info', 'diasfem.com',
         'fembad.org', 'moviemaniac.org', 'albavido.xyz', 'ncdnstm.com', 'fembed-hd.com', 'superplayxyz.club', 'cinegrabber.com',
         'ndrama.xyz', 'javstream.top', 'javpoll.com', 'suzihaza.com', 'fembed.net', 'filepup.net', 'flashx.tv', 'flashx.to',
         'flashx.sx', 'flashx.bz', 'flashx.cc', 'gamovideo.com', 'gofile.io', 'googlevideo.com', 'googleusercontent.com',
         'get.google.com', 'plus.google.com', 'googledrive.com', 'drive.google.com', 'docs.google.com', 'youtube.googleapis.com',
         'bp.blogspot.com', 'blogger.com', 'hdvid.tv', 'hdvid.fun', 'vidhdthe.online', 'hexupload.net', 'holavid.com', 'hugefiles.net',
         'hugefiles.cc', 'hxload.to', 'hxload.co', 'hxload.io', 'indavideo.hu', 'jetload.net', 'jetload.to', 'k2s.cc', 'lbry.tv',
         'odysee.com', 'madiator.com', 'letsupload.io', 'letsupload.org', 'stream.lewd.host', 'mail.ru', 'my.mail.ru', 'm.my.mail.ru',
         'videoapi.my.mail.ru', 'api.video.mail.ru', 'megaup.net', 'megogo.net', 'megogo.ru', 'mixdrop.co', 'mixdrop.to', 'mixdrop.sx',
         'mixdrop.bz', 'mp4upload.com', 'mycloud.to', 'mcloud.to', 'mystream.la', 'mystream.to', 'mstream.xyz', 'mstream.cloud',
         'mstream.fun', 'mstream.press', 'ninjastream.to', 'ok.ru', 'odnoklassniki.ru', 'onlystream.tv', 'pandafiles.com',
         'peertube.tv', 'peertube.co.uk', 'peertube.uno', 'pixeldrain.com', 'pkspeed.net', 'playtube.ws', 'playwire.com',
         'racaty.net', 'rovideo.net', 'rumble.com', 'rutube.ru', 'videos.sapo.pt', 'saruch.co', 'sibnet.ru', 'streamable.com',
         'streamingcommunity.xyz', 'streamingcommunity.one', 'streamingcommunity.vip', 'streamingcommunity.work', 'streamingcommunity.name',
         'streamingcommunity.video', 'streamingcommunity.live', 'streamingcommunity.tv', 'streamingcommunity.space', 'streamingcommunity.art',
         'streamingcommunity.fun', 'streamingcommunity.website', 'streamlare.com', 'streamrapid.ru', 'rabbitstream.net',
         'sbembed.com', 'sbembed1.com', 'sbplay.org', 'sbvideo.net', 'streamsb.net', 'sbplay.one', 'cloudemb.com', 'playersb.com',
         'tubesb.com', 'sbplay1.com', 'embedsb.com', 'watchsb.com', 'sbplay2.com', 'japopav.tv', 'viewsb.com', 'streamtape.com',
         'strtape.cloud', 'streamtape.net', 'streamta.pe', 'streamtape.site', 'strcloud.link', 'strtpe.link', 'streamtape.cc',
         'scloud.online', 'stape.fun', 'streamty.com', 'streamvid.co', 'streamz.cc', 'streamz.vg', 'streamzz.to', 'streamz.ws',
         'supervideo.tv', 'truhd.xyz', 'tubitv.com', 'tudou.com', 'tune.pk', 'tune.video', 'tusfiles.net', 'tusfiles.com',
         'tvlogy.to', 'uploadflix.org', 'upstream.to', 'uptobox.com', 'uptostream.com', 'upvideo.to', 'videoloca.xyz',
         'tnaket.xyz', 'makaveli.xyz', 'highload.to', 'userload.co', 'veoh.com', 'vev.io', 'vev.red', 'vidbom.com', 'vidbem.com',
         'vidbm.com', 'vedpom.com', 'vedbom.com', 'vedbom.org', 'vadbom.com', 'vidbam.org', 'myviid.com', 'myviid.net',
         'myvid.com', 'vidshare.com', 'vedsharr.com', 'vedshar.com', 'vedshare.com', 'vadshar.com', 'vidshar.org', 'vidcloud9.com',
         'vidnode.net', 'vidnext.net', 'vidembed.net', 'vidembed.cc', 'vidembed.io', 'vidembed.me', 'videa.hu', 'videakid.hu',
         'thevideobee.to', 'videobin.co', 'videohost2.com', 'videomega.co', 'videoseyred.in', 'videovard.sx', 'videovard.to',
         'videowood.tv', 'byzoo.org', 'playpanda.net', 'videozoo.me', 'videowing.me', 'easyvideo.me', 'play44.net', 'playbb.me',
         'video44.net', 'videozupload.net', 'videzup.pl', 'videzup.top', 'vidia.tv', 'vidlox.tv', 'vidlox.me', 'vidlox.xyz',
         'vidmojo.net', 'vidorg.net', 'vidpiz.xyz', 'vidstore.me', 'vimeo.com', 'player.vimeo.com', 'viuclips.net', 'veuclips.com',
         'vivo.sx', 'vivo.st', 'vk.com', 'videoslala.com', 'videoslala.net', 'voe.sx', 'vshare.eu', 'yourupload.com', 'yucache.net',
         'youtube.com', 'youtu.be', 'youtube-nocookie.com', 'aliez.me', 'anonfiles.com', 'bayfiles.com', 'avideo.host', 'banned.video',
         'freeworldnews.tv', 'electionnight.news', 'futurenews.news', 'bitchute.com', 'brighteon.com', 'chromecast.video',
         'cloudb.me', 'cloudb2.me', 'cloudvideo.tv', 'datemule.co', 'datemule.com', 'downace.com', 'duckstream.co', 'elupload.com',
         'entervideo.net', 'eplayvid.com', 'filerio.in', 'files.im', 'gogo-play.net', 'gomoplayer.com', 'tunestream.net',
         'xvideosharing.com', 'gounlimited.to', 'hxfile.co', 'itemfix.com', 'liivideo.com', 'myfeminist.com', 'myupload.co',
         'newtube.app', 'nxload.com', 'oogly.io', 'playhd.one', 'playdrive.xyz', 'putload.tv', 'shitmovie.com', 'send.cm',
         'sendfox.org', 'sendvid.com', 'speedostream.com', 'speedvideo.net', 'speedwatch.io', 'streamani.net', 'streamhub.to',
         'streamoupload.com', 'streamwire.net', 'superitu.com', 'turboviplay.com', 'emturbovid.com', 'uqload.com', 'userscloud.com',
         'vidbob.com', 'vidcloud.co', 'vidcloud.pro', 'vidcloud.is', 'videoapne.co', 'videooo.news', 'videos.sh', 'videoz.me',
         'vidfast.co', 'vidmoly.me', 'vidmoly.to', 'vidmoly.net', 'vidmx.xyz', 'vidoza.net', 'vidoza.co', 'vidspace.io',
         'vidstreaming.io', 'vidto.me', 'vidto.se', 'viduplayer.com', 'vidwatch3.me', 'vidwatch4.me', 'vidwatch.me', 'vidzi.tv',
         'vidzi.nu', 'vkprime.com', 'vkspeed.com', 'speedwatch.us', 'vlare.tv', 'vtube.to', 'vudeo.net', 'vudeo.io', 'vupload.com',
         'vup.to', 'watchvideo.us', 'watchvideo2.us', 'watchvideo3.us', 'watchvideo4.us', 'watchvideo5.us', 'watchvideo6.us',
         'watchvideo7.us', 'watchvideo8.us', 'watchvideo9.us', 'watchvideo10.us', 'watchvideo11.us', 'watchvideo12.us',
         'watchvideo13.us', 'watchvideo14.us', 'watchvideo15.us', 'watchvideo16.us', 'watchvideo17.us', 'watchvideo18.us',
         'watchvideo19.us', 'watchvideo20.us', 'watchvideo21.us', 'weshare.me', 'wstream.video', 'disk.yandex.ru', 'yadi.sk',
         'youdbox.com', 'youdbox.net', 'youdbox.org', 'yodbox.com']
hostspr = ['1fichier.com', 'oboom.com', 'rapidgator.net', 'rg.to', 'uploaded.net', 'uploaded.to', 'ul.to', 'filefactory.com',
           'nitroflare.com', 'turbobit.net', 'uploadrocket.net']
