# Ten runner tworzy binarki i wrzuca do repo binarnego 
# Jeden job

name: MatrixZips

# Wyzwalanie  na push pliku addon.xml  do gałęzi main
# (podniesienie wersji)

on:
  push:
    branches:    
      - 'main'
    paths:
      - 'matrix/*/addon.xml'        

jobs:
    build:
        env:
           commitmsg: ${{ github.event.head_commit.message }} # ostatni commit-message   
        runs-on: ubuntu-latest    
        steps:                      
          - name: checkout content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2            
            with:
              python-version: 3.8 #install the python needed
          - name: make zips 
#      uruchamianie skryptu generatora python 
#      Mój tworzy folder zips a w nich już foldery z binarkami i pliki addons.xml i addons.xml.md5
            run: |
              cd matrix
              python repo_generator.py     
# Commit do drugiego repo              
          - name: Pushes to another repository
            id: push_directory
            uses: cpina/github-action-push-to-another-repository@main
            env:
              API_TOKEN_GITHUB: ${{ secrets.UPLOAD }}     # utworzony secret - dostęp do repo 
            with:
              source-directory: matrix/zips/              # w repo źródłowym
              target-directory: v19                       # w repo docelowym
              destination-github-username: 'lantash77'    # użytkownik repo docelowego
              destination-repository-name: 'lantash-repo' # nazwa repo docelowego
              user-email: github-actions@github.com
              user-name: 'autobot'                        # autor commitu
              commit-message: ${{ env.commitmsg }}        # commit-message  
              target-branch: main                         # gałąź 
          - name: Test get variable exported by push-to-another-repository
            run: echo $DESTINATION_CLONED_DIRECTORY

         

        
          
            
            
      
